name: Deploy do Vite no GitHub Pages

on:
  push:
    branches: ['main'] # Substitua por 'master' se a sua branch principal for master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Mude para 'pnpm' ou 'yarn' se usar outro gerenciador

      - name: Instalar dependências
        run: npm ci

      - name: Gerar o Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # O Vite gera a pasta 'dist' por padrão

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
